# Generated by Django 6.0 on 2026-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovereditem',
            name='is_recovered',
            field=models.BooleanField(default=False),
        ),
    ]
