# Generated by Django 6.0 on 2026-01-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_recovereditem_is_recovered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recovereditem',
            name='is_recovered',
        ),
        migrations.AddField(
            model_name='recovereditem',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Wallets', 'Wallets/Bags'), ('Keys', 'Keys'), ('Pets', 'Pets'), ('Documents', 'ID/Documents'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
