# Generated by Django 6.0 on 2026-01-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_recovereditem_is_recovered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recovereditem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='recovereditem',
            name='finder_contact',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recovereditem',
            name='finder_name',
            field=models.CharField(default='Anonymous', max_length=100),
            preserve_default=False,
        ),
    ]
