# Generated by Django 6.0 on 2026-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_recovereditem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovereditem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recovereditem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
